security:
    encoders:
        App\Entity\User1:
            algorithm:  bcrypt
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory: { memory: null }
        in_database:
            entity:
                class:  App\Entity\User1
                property:  email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin
            anonymous: true

            provider: in_database

            form_login:
                login_path: admin_account_login
                check_path: admin_account_login
                default_target_path: admin_dashboard

            logout:
                path: admin_account_logout
                target: admin_account_login
        main:
            anonymous: lazy

            provider:  in_database

            form_login:
                login_path: account_login2
                check_path: account_login2

            logout:
                path: account_logout
                target: account_login2

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
         - { path: ^/admin, roles: ROLE_ADMIN, requires_channel: https }
        # - { path: ^/profile, roles: ROLE_USER } 
        # catch all other URLs
         - { path: ^/, roles: ROLE_USER, requires_channel: https }

    # La partie role_hierarchy contient la hiérarchie des rôles
    # Un éditeur sera également utilisateur
    # Un administrateur sera également éditeur et donc utilisateur
    role_hierarchy:
        #ROLE_EDITOR: ROLE_USER
        #ROLE_ADMIN: ROLE_EDITOR
        ROLE_ADMIN: ROLE_USER
